apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: git-log-to-json-changelog
  annotations:
    github.com/project-slug: grigoryvp/git-log-to-json-changelog
spec:
  type: other
  lifecycle: unknown
  owner: guests
